### ISSUE TITLE
Question: usage without unsafe

### ISSUE THREAD

**Issue by bsr203** [spacemonkeygo/monkit#4]
Hi,

Is there a way to remove the use of `unsafe` package (trace.go, registery.go, watch.go) so I can use this package in sandboxed app engine environment.  I could either maintain a fork, or try to add build flags (`/ +build !appenginevm`) to make it work. I probably can't request system statistics, but like to use other features like tracing. Please let me know is it easy to replace `unsafe.Pointer` usages.

thanks.
bsr.

**Comment by jtolds** [comment]
Unfortunately, the unsafe usages are currently critical (paradoxically) to safe multithreaded usage. The only reason for the unsafe.Pointer usages is atomic compare and swap. We try to use lockless datastructures where possible for performance in these hotpaths, and compare and swap allows us to avoid mutexes. I don't know of a good way to performantly get the same behavior. 

That said, there's no reason we can't write a build-environment specific pointer compare-and-swap implementation that uses unsafe when available and mutexes for appengine. I agree that supporting appengine is a huge benefit. I'll take a look at fixing this soon.

**Comment by bsr203** [comment]
wow... thank you for the quick response and help to get it working on appengine. Though I used go for quite long, didn't try the low level constructs and not an expert on concurrency primitives.  Thanks again and I would attach the example I am trying out.

**Comment by bsr203** [comment]
[monitor.zip](https://github.com/spacemonkeygo/monkit/files/419507/monitor.zip)

This is about 12 mb, as I included the all the packages installed through go get. 

Few notes:
1. I initially tried to make the reverse proxy work, but I think it is restricted. there is a [reference](https://groups.google.com/forum/#!searchin/google-appengine-go/NewSingleHostReverseProxy%7Csort:relevance/google-appengine-go/y5pQ0kb6zxk/0rF6ZUQKBAAJ) of it in the mailing list.
2. GAE docs are bit confusing as most of the examples point to managed Vm, and I think I used the new GCE example (which uses appengine.Main())
3. The directory structure is to make sure the dependencies are outside the directory where `app.yaml` lives. Else, there will be error from all the packages installed by go get (eg: `x/net/context` installs tons of other packages which depends on `syscall`)

 to run.

1. extract the zip
2. cd monitor
3. export GOPATH=`pwd`/external
4. goapp serve app/src

goapp is in my $PATH, and installed from https://cloud.google.com/appengine/downloads
mine is (osx) https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_darwin_amd64-1.9.40.zip

once startup successfully, http://localhost:8080/ gives a `hello...` message
`http://localhost:8080/proxy` is the failed attempt to make proxy work.

`monkit` is not installed, once installed and enable by removing the commented out lines, it gives error.

Let me know anyway I can help. For app engine compute engine vm, the correct env flag is `appenginevm`. like `/ +build !appenginevm`

**Comment by bsr203** [comment]
I just found another package for tracing. couldn't find any sync or unsafe operation. In `monkit`unsafe may be used for other functionalities, but thought you may interested (I havn't tried it but I think it just concerned with trace collection). 
https://github.com/uber-common/opentracing-go

**Comment by jtolds** [comment]
Yeah, we're almost done fixing this. Should have a patchset up soon.

**Comment by zeebo** [comment]
Ok, building with the appengine tag should remove all usages of unsafe. Please let us know if there's any bugs or whatever.

**Comment by bsr203** [comment]
thanks Jeff. It works great. I have some followup qn, and will ask separately.
