### ISSUE TITLE
Question: trace collector per http request

### ISSUE THREAD

**Issue by bsr203** [spacemonkeygo/monkit#5]
hi,

I do some RPC stats similar to `appstats` and push the result to memcache and later collect it. I am not sure about using `monkit-zipkin` and setting up an external system yet, but may write a small SPA to display trace and annotations.

What is the best way to collect trace from `context` which is created per request. Do I need to use the registry/observer and all.

thanks.
bsr

**Comment by bsr203** [comment]
Further looking at the code, I see interfaces like `SpansJSON`, which may be ok as well to get all the spns and then clear after the request. I also see`SpanFromCtx`, getting it from the top level context may also an option. Let me know if there a better way.

I found `SpansJSON` is giving empty response, even with some tracing enabled. Lokking further. thanks again.

**Comment by jtolds** [comment]
So, provided that all of your functions look like this:

  func MyFunc(ctx context.Context, ...) (..., err error) {
    defer mon.Task()(&ctx)(&err)
    ...
  }

all you need to do to collect all the traces for zipkin is somewhere during setup:

  collector, err := trace.NewUDPCollector(server_addr, 128)
  if err != nil {
    return err
  }
  trace.RegisterZipkin(monkit.Default, collector, trace.Options{...})

if you want to be able to collect a specific trace, you can certainly use the built-in `present` webhandler, as described in the README.md

if you want to handle all traces yourself, you can do

  monkit.Default.ObserveTraces(func (t *monkit.Trace) {
    t.ObserveSpans(something that implements monkit.SpanObserver)
  })

**Comment by jtolds** [comment]
the SpansJSON stuff is for the `present` webhandler, as described in README.md (https://github.com/spacemonkeygo/monkit/blob/master/README.md#tracing)

**Comment by bsr203** [comment]
thanks @jtolds for the detailed response. I tried `ObserveTraces` and it worked great, except in my case, I need the response after the request is processed as most of the services (including memcache,..) is request bound and can only execute with a valid context.

```
func (v *VLite) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := appengine.NewContext(r)
	defer mon.TaskNamed("main")(&ctx)(nil)

	v.HandleHTTP(ctx, w, r)
       monkit.SpanFromCtx(ctx) // this works !!
}

````
above works, and do you think it is safe to use that way? 

will close this after the response. thanks again for your time and patience.

**Comment by jtolds** [comment]
Oh yeah totally, you can always pull the current span using SpanFromCtx. Unfortunately, it won't actually let you collect all of the spans that started in v.HandleHTTP, since most of them will have returned. (*Span).Children only keeps track of live Spans.

If you want to collect all spans in some child function, you can do:

```
func (v *VLite) ServeHTTP(w http.ResponseWriter, r *http.Request) {
    spans := present.CollectSpans(appengine.NewContext(r), func(ctx context.Context) {
        defer mon.TaskNamed("main")(&ctx)(nil)
        v.HandleHTTP(ctx, w, r)
    })
    ... do something with spans
}
```

present.CollectSpans is pretty useful. perhaps that should be a top-level monkit method

**Comment by jtolds** [comment]
last comment updated to fix a small bug - CollectSpans only works if the context is already being traced, so I moved mon.TaskNamed from inside the callback to outside.

**Comment by jtolds** [comment]
based on what you're doing, you might also be interested in https://godoc.org/gopkg.in/spacemonkeygo/monkit-zipkin.v2#TraceHandler

you can use the TraceHandler to propagate traces across processes and services without necessarily hooking up zipkin

**Comment by bsr203** [comment]
thanks again for being super nice and patient :-) you guys are pretty awesome :-)

Cheers. bsr.

**Comment by jtolds** [comment]
ah geez, thanks!
