### ISSUE TITLE
Update present/http.go's monkit old dependency.

### ISSUE THREAD

**Issue by shuoli84** [spacemonkeygo/monkit#7]
I am evaluating monkit right now. 

One problem is: it has some dependencies points to the old package. E.g: present/http.go's 
```golang
	"github.com/spacemonkeygo/errors"
```
 This brings in golang's old context library etc. Is it something we can clean it? 

Awesome work BTW.

**Comment by jtolds** [comment]
Whoops! updated the errors package. Lemme know if that's not fixed.
